name: All ci

on:
  workflow_dispatch:

jobs:
  call-lint-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./.github/workflows/lint_workflow.yml@a5a1fa312c219413d2278632a7ae4919c06aa580"